### ISSUE TITLE
Does not build on development SBCL - bad lambda list in DEFXMLPARSER

### ISSUE THREAD

**Issue by quicklisp** [hargettp/hh-aws#2]
`defxmlparser` has something like this:

```
`&key ((:finish finish-method nil))`
```

It's supposed to be this:

```
`&key ((:finish finish-method) nil)`
```

SBCL has recently been updated to detect this kind of error, so hh-aws no longer builds with the latest development version of sbcl.

A build log is here: http://report.quicklisp.org/2015-07-28/failure-report/hh-aws.html

**Comment by hargettp** [comment]
thanks, Zach! will check it out :)
